<template>
  <v-container class="grey lighten-5">
    <v-row
      class="mb-12"
      no-gutters
    >
      <v-col md="3" offset-sm="">
        <v-card
          class="pa-2"
          outlined
          tile
        >
          lmao
        </v-card>
      </v-col>
      <v-col
        md="3"
        offset-sm="6"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          lmao
        </v-card>
      </v-col>
    </v-row>
    
    <v-row
      class="mb-10"
      no-gutters
    >
      <v-col
        md="3"
        offset-sm="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          ji
        </v-card>
      </v-col>
      
      <v-col
        md="3"
        offset-sm=""
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          shankara
        </v-card>
      </v-col>
    </v-row>

    <v-row >
      <v-col
        md="12"
        offset-sm=""
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          bhole----------nath----------shankara
        </v-card>
      </v-col>
    </v-row>

    <v-row
      class="mb-12"
      no-gutters
    >
      <v-col md="3" offset-sm="">
        <v-card
          class="pa-2"
          outlined
          tile
        >
          jai
        </v-card>
      </v-col>
      <v-col
        md="3"
        offset-sm="6"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          trilok nath
        </v-card>
      </v-col>
    </v-row>
    
    <v-row
      class="mb-10"
      no-gutters
    >
      <v-col
        md="3"
        offset-sm="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          shambu
        </v-card>
      </v-col>
      
      <v-col
        md="3"
        offset-sm=""
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          jai
        </v-card>
      </v-col>
    </v-row>

    <v-row >
      <v-col
        md="12"
        offset-sm=""
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          lmao--------------------shankara
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>